### ISSUE TITLE
error: bad value (native) for -march switch

### ISSUE THREAD

**Issue by dvn-dvn** [hyperboria/cjdns#11]
output from ./do 
```
### Installing node.js (you can bypass this step by manually installing node.js v0.8.15 or newer
)


==> Downloading http://nodejs.org/dist/v0.10.24/node-v0.10.24-linux-arm-pi.tar.gz with wget... D
ONE!
==> Verifying the checksum of the downloaded archive... DONE!
==> Extracting the downloaded archive... DONE!

Initialize 10ms
Copy dependencies
Link time optimization not supported [cc1: error: bad value (native) for -march switch
]
Build NaCl
Creating directories
cc1: error: bad value (native) for -march switch

Total build time: 3553ms.

/root/testing/cjdns/build_linux/dependencies/cnacl/node_build/RandomBytes.js:13
        if (retCode) { throw new Error('failed to compile'); }
                             ^
Error: failed to compile
    at /root/testing/cjdns/build_linux/dependencies/cnacl/node_build/RandomBytes.js:13:30
    at /root/testing/cjdns/node_build/builder.js:85:13
    at ChildProcess.<anonymous> (/root/testing/cjdns/node_build/Semaphore.js:7:30)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
./do  4.91s user 3.23s system 117% cpu 6.906 total
```

/proc/cpuinfo
```
Processor       : ARMv7 Processor rev 4 (v7l)
processor       : 0
BogoMIPS        : 2004.17

processor       : 1
BogoMIPS        : 2011.05

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva id
ivt 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4

Hardware        : sun7i
Revision        : 0000
Serial          : 0702b4b4544948488048566616516605
```

**Comment by lgierth** [comment]
This appears to be fixed by updating to GCC >= 4.7
