### ISSUE TITLE
Assertion failure [NodeStore.c:722] [(nextLink != parentLink)]

### ISSUE THREAD

**Issue by lgierth** [hyperboria/cjdns#110]
```
Assertion failure [NodeStore.c:722] [(nextLink != parentLink)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff7fed740 (LWP 29197)]
0x00007ffff7625cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Thread 2 (Thread 0x7ffff7fed740 (LWP 29197)):
#0  0x00007ffff7625cc9 in __GI_raise (sig=sig@entry=6)
---Type <return> to continue, or q <return> to quit---    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff76290d8 in __GI_abort () at abort.c:89
#2  0x000055555555a8d5 in Assert_failure (
    format=format@entry=0x5555555d0690 "Assertion failure [%s:%d] [%s]\n")
    at util/Assert.c:32
#3  0x0000555555578fb0 in firstHopInPath (label=label@entry=21423581854, 
    outLink=outLink@entry=0x7fffffffe3c0, 
    parentLink=parentLink@entry=0x555555882f48, store=<optimized out>)
    at dht/dhtcore/NodeStore.c:722
#4  0x000055555557a18b in findClosest (store=0x5555557f3a78, 
    parentLink=0x555555882f48, output=<synthetic pointer>, path=21423581854)
    at dht/dhtcore/NodeStore.c:754
#5  NodeStore_linkForPath (nodeStore=0x5555557f3a78, path=<optimized out>)
    at dht/dhtcore/NodeStore.c:1446
#6  0x000055555558bb17 in discoveredPath (pf=0x55555580ca88, 
    msg=0x5555558cc618) at dht/Pathfinder.c:344
#7  incomingFromEventIf (msg=0x5555558cc618, eventIf=0x55555580ca88)
    at dht/Pathfinder.c:420
#8  0x000055555556d064 in Iface_send (msg=0x5555558cc618, iface=0x55555580cdb8)
    at ./interface/Iface.h:69
#9  timeoutTrigger (vASynchronizer=0x55555580cdb8)
    at interface/ASynchronizer.c:69
#10 0x00005555555ccbe1 in uv__run_timers (loop=loop@entry=0x5555557f02b0)
---Type <return> to continue, or q <return> to quit---    at ../src/unix/timer.c:146
#11 0x00005555555c32a2 in uv_run (loop=0x5555557f02b0, 
    mode=mode@entry=UV_RUN_DEFAULT) at ../src/unix/core.c:275
#12 0x000055555555ff15 in EventBase_beginLoop (eventBase=0x5555557f0268)
    at util/events/libuv/EventBase.c:83
#13 0x00005555555aadd1 in Core_main (argc=<optimized out>, 
    argv=<optimized out>) at admin/angel/Core.c:333
#14 0x0000555555559393 in main (argc=3, argv=0x7fffffffed68)
    at client/cjdroute2.c:510


Core exited with status [0], signal [9]
```

**Comment by lgierth** [comment]
Another one of this: https://ncry.pt/p/hGBn#IN9CXNRy7f0Fw3IC92XYEkCg6qVQA297k6QI3lyVpHg
