### ISSUE TITLE
Assertion failure [NodeStore.c:1017] [(pathParentChild == 1)]

### ISSUE THREAD

**Issue by lgierth** [hyperboria/cjdns#111]
```
Assertion failure [NodeStore.c:1017] [(pathParentChild == 1)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff7feb740 (LWP 20903)]
0x00007ffff7625cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Thread 2 (Thread 0x7ffff7feb740 (LWP 20903)):
#0  0x00007ffff7625cc9 in __GI_raise (sig=sig@entry=6)
---Type <return> to continue, or q <return> to quit---    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff76290d8 in __GI_abort () at abort.c:89
#2  0x000055555555a8d5 in Assert_failure (
    format=format@entry=0x5555555d0690 "Assertion failure [%s:%d] [%s]\n")
    at util/Assert.c:32
#3  0x000055555557eb1f in discoverLink (inverseLinkEncodingFormNumber=0, 
    child=0x5555558df2a8, path=333152542, store=0x5555557f3948)
    at dht/dhtcore/NodeStore.c:1017
#4  NodeStore_discoverNode (nodeStore=0x5555557f3948, 
    addr=addr@entry=0x7fffffffe480, scheme=<optimized out>, 
    inverseLinkEncodingFormNumber=0, milliseconds=milliseconds@entry=332)
    at dht/dhtcore/NodeStore.c:1334
#5  0x000055555558259e in onResponseOrTimeout (data=<optimized out>, 
    milliseconds=332, vping=0x5555558a60f8) at dht/dhtcore/RouterModule.c:516
#6  0x000055555558233a in callback (ping=0x5555558acc28, data=0x5555559888e8)
    at util/Pinger.c:55
#7  Pinger_pongReceived (data=0x5555559888e8, pinger=<optimized out>)
    at util/Pinger.c:167
#8  0x00005555555827e1 in handleIncoming (message=0x7fffffffe440, 
    vcontext=0x5555558174a8) at dht/dhtcore/RouterModule.c:461
#9  0x000055555557612a in DHTModuleRegistry_handleIncoming (
    message=message@entry=0x7fffffffe440, registry=<optimized out>)
    at dht/DHTModuleRegistry.c:63
---Type <return> to continue, or q <return> to quit---#10 0x000055555558bcb2 in incomingMsg (pf=0x55555580ca88, msg=0x555555843d08)
    at dht/Pathfinder.c:392
#11 incomingFromEventIf (msg=0x555555843d08, eventIf=0x55555580ca88)
    at dht/Pathfinder.c:421
#12 0x000055555556d064 in Iface_send (msg=0x555555843d08, iface=0x55555580cdb8)
    at ./interface/Iface.h:69
#13 timeoutTrigger (vASynchronizer=0x55555580cdb8)
    at interface/ASynchronizer.c:69
#14 0x00005555555ccbe1 in uv__run_timers (loop=loop@entry=0x5555557f02b0)
    at ../src/unix/timer.c:146
#15 0x00005555555c32a2 in uv_run (loop=0x5555557f02b0, 
    mode=mode@entry=UV_RUN_DEFAULT) at ../src/unix/core.c:275
#16 0x000055555555ff15 in EventBase_beginLoop (eventBase=0x5555557f0268)
    at util/events/libuv/EventBase.c:83
#17 0x00005555555aadd1 in Core_main (argc=<optimized out>, 
    argv=<optimized out>) at admin/angel/Core.c:333
#18 0x0000555555559393 in main (argc=3, argv=0x7fffffffed68)
    at client/cjdroute2.c:510


Core exited with status [0], signal [9]
```

**Comment by lgierth** [comment]
Another one of this kind, with logs: http://cjdns.ncry.pt/p/ZFBn#lXvcbyQ3CzHbG7yIcMeXzBivW-7aALJIRxD1elAC-BI

**Comment by lgierth** [comment]
Last log lines:

```
1457718117 DEBUG NodeStore.c:1296 Discover node [fc38:7233:d541:c707:d8d5:8a60:4da9:78a9@0000.c21c.b965.5c29]
1457718117 DEBUG NodeStore.c:810 discoverLinkC( [fc26:c07e:0870:90ea:bfe9:f941:0314:77b7]->[fc38:7233:d541:c707:d8d5:8a60:4da9:78a9] [0000.0000.0000.0001] )
1457718117 DEBUG NodeStore.c:129 link[fc7c:6025:dce5:af5b:7a3f:8343:b581:c851]->[fc26:c07e:0870:90ea:bfe9:f941:0314:77b7] [0000.0000.0000.00c2] Unlinking node for path change
1457718117 DEBUG NodeStore.c:553 Linking [fc7c:6025:dce5:af5b:7a3f:8343:b581:c851] with [fc38:7233:d541:c707:d8d5:8a60:4da9:78a9] with label fragment [0000.0000.0000.00c2]
```

**Comment by christianbundy** [comment]
Just had this as well:

```
Assertion failure [NodeStore.c:1048] [(pathParentChild == 1)]
```
