### ISSUE TITLE
When trying to use most of the tools under /tools

### ISSUE THREAD

**Issue by dalanmiller** [hyperboria/cjdns#114]
I assume it's using the `node` that's on my path which is at version `5.7.1`.
```
/Users/user/repos/cjdns/tools/lib/cjdnsadmin/cjdnsadmin.js:149
                    Object.keys(ret.availableFunctions).forEach(function (funcName) {
                           ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at /Users/dalanmiller/repos/cjdns/tools/lib/cjdnsadmin/cjdnsadmin.js:149:28
    at Object.callback (/Users/dalanmiller/repos/cjdns/node_modules/nthen/lib/nthen.js:16:22)
    at Socket.<anonymous> (/Users/dalanmiller/repos/cjdns/tools/lib/cjdnsadmin/cjdnsadmin.js:191:17)
    at emitTwo (events.js:100:13)
    at Socket.emit (events.js:185:7)
    at UDP.onMessage (dgram.js:523:8)
```

**Comment by lgierth** [comment]
This might be an Admin API password mismatch. If you have `~/.cjdnsadmin` file, remove it, and make sure that `admin.password` in your config is `"NONE"`.

**Comment by Kubuxu** [comment]
If it is the issue we should have nice error message for that.

**Comment by dalanmiller** [comment]
Got it working after your instructions @lgierth but agreed that some instructions would be helpful :+1:

**Comment by ansuz** [comment]
I agree with @Kubuxu that we should have better error handling, but your stack trace doesn't have any information about what command(s) you were trying to run.

I'd like to be able to reproduce your problem to start. I do not have a .cjdnsadmin file either, and most of the commands work (on crashey branch).
