### ISSUE TITLE
Crash at start on master / 20150308

### ISSUE THREAD

**Issue by viric** [hyperboria/cjdns#13]
Just starting cjdroute, it crashes.

It may be relevant that I'm running a cjdroute 1) as non-root and 2) without tun interface.

```
(gdb) bt
#0  incomingFromUpperDistributorIf () at ./interface/Iface.h:106
#1  0x00007f33c3d0f85d in incomingFromSessionManagerIf () at ./interface/Iface.h:70
#2  0x00007f33c3d0e30c in Iface_next () at ./interface/Iface.h:70
#3  0x00007f33c3d0a71e in incomingFromSwitchIf () at ./interface/Iface.h:70
#4  0x00007f33c3d0e114 in incomingFromSwitchIf () at ./interface/Iface.h:70
#5  0x00007f33c3cd16f0 in receiveMessage () at ./interface/Iface.h:70
#6  0x00007f33c3cd769b in receivedPostCryptoAuth () at ./interface/Iface.h:70
#7  0x00007f33c3cd7dce in handleIncomingFromWire () at net/InterfaceController.c:685
#8  0x00007f33c3cc2235 in incoming () at ./interface/Iface.h:70
#9  0x00007f33c3d35b83 in uv__udp_io () at ../src/unix/udp.c:219
#10 0x00007f33c3d36cf7 in uv__io_poll () at ../src/unix/linux-core.c:271
#11 0x00007f33c3d2c077 in uv_run () at ../src/unix/core.c:284
#12 0x00007f33c3cbd606 in EventBase_beginLoop ()
#13 0x00007f33c3d11aae in Core_main () at admin/angel/Core.c:373
#14 0x00007f33c3cb87d6 in main () at admin/angel/cjdroute2.c:419
```

**Comment by lgierth** [comment]
I'm closing since 2 months have passed without an update or resolution. Please reopen if this issue still exists.
