### ISSUE TITLE
Compilation fails on Raspbian Jessie

### ISSUE THREAD

**Issue by benhylau** [hyperboria/cjdns#131]
Compiling on Pi 2 Raspbian Jessie started failing with this error. This used to work.

```
$ NO_TEST=1 Seccomp_NO=1 ./do
...

/home/pi/cjdns/node_build/builder.js:485
            if (err) { throw err; }
                             ^
Error: gcc -c -x cpp-output -o build_linux/tunnel_RouteGen_admin_c.o -std=c99 -Wall -Wextra -Werror -Wno-pointer-sign -pedantic -D linux=1 -D CJD_PACKAGE_VERSION="unknown" -Wno-unused-parameter -D Log_DEBUG -g -D NumberCompress_TYPE=v3x5x8 -D Identity_CHECK=1 -D Allocator_USE_CANARIES=1 -D PARANOIA=1 -DHAS_ETH_INTERFACE=1 -fPIE -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -s -static -Wall -mfpu=neon -mcpu=cortex-a7 -mtune=cortex-a7 -fomit-frame-pointer -marm -fno-stack-protector -fstack-protector-all -Wstack-protector -O3 build_linux/tunnel_RouteGen_admin_c.o.i

tunnel/RouteGen_admin.c: In function 'commit':
tunnel/RouteGen_admin.c:181:11: error: variable 'error' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
     char* error = "none";
           ^
cc1: all warnings being treated as errors

    at error (/home/pi/cjdns/node_build/builder.js:53:15)
    at /home/pi/cjdns/node_build/builder.js:122:22
    at /home/pi/cjdns/node_build/builder.js:92:13
    at ChildProcess.<anonymous> (/home/pi/cjdns/tools/lib/Semaphore.js:7:30)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Socket.<anonymous> (child_process.js:968:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

Also noticed that **tunnel/RouteGen_admin.c** isn't on https://github.com/cjdelisle/cjdns anymore.

**Comment by Kubuxu** [comment]
It is on crashey: https://github.com/cjdelisle/cjdns/blob/crashey/tunnel/RouteGen_admin.c

**Comment by ghost** [comment]
Yeah and crashey should also contain a fix for this

**Comment by benhylau** [comment]
Thanks I will check tonight and close this if it's fixed.

**Comment by benhylau** [comment]
Yes this is fixed on crashey. Thanks.
