### ISSUE TITLE
cjdroute segfault in discoverLinkC

### ISSUE THREAD

**Issue by nsjph** [hyperboria/cjdns#137]
Thread 2.1 "cjdroute" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fec700 (LWP 2018)]
discoverLinkC (store=store@entry=0x5555557fcac8, closestKnown=<optimized out>, 
    pathKnownParentChild=pathKnownParentChild@entry=64099, child=child@entry=0x5555559330c8, 
    discoveredPath=discoveredPath@entry=64099, 
    inverseLinkEncodingFormNumber=inverseLinkEncodingFormNumber@entry=2)
    at dht/dhtcore/NodeStore.c:868
868                 parent = closest->child;
(gdb) backtrace
#0  discoverLinkC (store=store@entry=0x5555557fcac8, closestKnown=<optimized out>, pathKnownParentChild=pathKnownParentChild@entry=64099,

```
child=child@entry=0x5555559330c8, discoveredPath=discoveredPath@entry=64099, inverseLinkEncodingFormNumber=inverseLinkEncodingFormNumber@entry=2)
at dht/dhtcore/NodeStore.c:868
```
#1  0x00005555555812ba in discoverLink (inverseLinkEncodingFormNumber=2, child=0x5555559330c8, path=64099, store=0x5555557fcac8)

```
at dht/dhtcore/NodeStore.c:1012
```
#2  NodeStore_discoverNode (nodeStore=0x5555557fcac8, addr=addr@entry=0x7fffffffdc60, scheme=<optimized out>, inverseLinkEncodingFormNumber=2,

```
milliseconds=milliseconds@entry=314) at dht/dhtcore/NodeStore.c:1335
```
#3  0x0000555555585ce2 in onResponseOrTimeout (data=<optimized out>, milliseconds=314, vping=0x5555558a5ed8) at dht/dhtcore/RouterModule.c:516
#4  0x0000555555585a7a in callback (ping=0x5555559cc238, data=0x55555597b1b8) at util/Pinger.c:55
#5  Pinger_pongReceived (data=0x55555597b1b8, pinger=<optimized out>) at util/Pinger.c:167
#6  0x0000555555585f41 in handleIncoming (message=0x7fffffffdc20, vcontext=0x5555557fceb8) at dht/dhtcore/RouterModule.c:461
#7  0x0000555555579b1a in DHTModuleRegistry_handleIncoming (message=message@entry=0x7fffffffdc20, registry=<optimized out>) at dht/DHTModuleRegistry.c:63
#8  0x000055555558f313 in incomingMsg (pf=0x555555817918, msg=0x5555558bc2b8) at dht/Pathfinder.c:399
#9  incomingFromEventIf (msg=0x5555558bc2b8, eventIf=0x555555817918) at dht/Pathfinder.c:430
#10 0x0000555555570c04 in Iface_send (msg=0x5555558bc2b8, iface=0x555555817c48) at ./interface/Iface.h:69
#11 timeoutTrigger (vASynchronizer=0x555555817c48) at interface/ASynchronizer.c:69
#12 0x00005555555d4e51 in uv__run_timers (loop=loop@entry=0x5555557fa2b0) at ../src/unix/timer.c:146
#13 0x00005555555cb172 in uv_run (loop=0x5555557fa2b0, mode=mode@entry=UV_RUN_DEFAULT) at ../src/unix/core.c:275
#14 0x000055555555fc75 in EventBase_beginLoop (eventBase=0x5555557fa268) at util/events/libuv/EventBase.c:83
#15 0x00005555555b1fcc in Core_main (argc=<optimized out>, argv=<optimized out>) at admin/angel/Core.c:379
#16 0x0000555555558f06 in main (argc=4, argv=0x7fffffffe548) at client/cjdroute2.c:536

(gdb) 

root@host:/opt/cjdns# git log | head -n 1
commit 116fa2aff419950403eba3530c4e2d2e63db8819

**Comment by nsjph** [comment]
environment at the time of segfault:
1. running cjdroute in gdb 
2. connected to one peer
3. constant ping6 to irc.fc00.io
4. no other manual cjdns activity
