### ISSUE TITLE
Crash on crashey in nodestore.c nextLink != parentLink

### ISSUE THREAD

**Issue by nsjph** [hyperboria/cjdns#139]
Assertion failure [NodeStore.c:723] [(nextLink != parentLink)]

Thread 2.1 "cjdroute" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff7fec700 (LWP 15910)]
0x00007ffff761e418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff761e418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff762001a in __GI_abort () at abort.c:89
#2  0x000055555555a286 in Assert_failure (format=format@entry=0x5555555d8b30 "Assertion failure [%s:%d] [%s]\n") at util/Assert.c:32
#3  0x000055555557d1a4 in firstHopInPath (label=label@entry=844597, outLink=outLink@entry=0x7fffffffd9c0, parentLink=parentLink@entry=0x555555867578,

```
store=0x5555557fca18) at dht/dhtcore/NodeStore.c:723
```
#4  0x000055555557d93b in findClosest (store=0x5555557fca18, parentLink=0x555555867578, output=<synthetic pointer>, path=844597)

```
at dht/dhtcore/NodeStore.c:755
```
#5  NodeStore_linkForPath (nodeStore=0x5555557fca18, path=<optimized out>) at dht/dhtcore/NodeStore.c:1447
#6  0x000055555558cbae in dhtResponseCallback (promise=<optimized out>, lagMilliseconds=<optimized out>, from=0x7fffffffdc60, result=0x555555887b98)

```
at dht/dhtcore/Janitor.c:243
```
#7  0x0000555555585d1b in onResponseOrTimeout (data=<optimized out>, milliseconds=221, vping=0x5555558a1b88) at dht/dhtcore/RouterModule.c:537
#8  0x0000555555585a7a in callback (ping=0x555555850bd8, data=0x555555869da8) at util/Pinger.c:55
#9  Pinger_pongReceived (data=0x555555869da8, pinger=<optimized out>) at util/Pinger.c:167
#10 0x0000555555585f41 in handleIncoming (message=0x7fffffffdc20, vcontext=0x55555580fca8) at dht/dhtcore/RouterModule.c:461
#11 0x0000555555579b1a in DHTModuleRegistry_handleIncoming (message=message@entry=0x7fffffffdc20, registry=<optimized out>) at dht/DHTModuleRegistry.c:63
#12 0x000055555558f313 in incomingMsg (pf=0x555555817918, msg=0x5555558474e8) at dht/Pathfinder.c:399
#13 incomingFromEventIf (msg=0x5555558474e8, eventIf=0x555555817918) at dht/Pathfinder.c:430
#14 0x0000555555570c04 in Iface_send (msg=0x5555558474e8, iface=0x555555817c48) at ./interface/Iface.h:69
#15 timeoutTrigger (vASynchronizer=0x555555817c48) at interface/ASynchronizer.c:69
#16 0x00005555555d4e51 in uv__run_timers (loop=loop@entry=0x5555557fa2b0) at ../src/unix/timer.c:146
#17 0x00005555555cb172 in uv_run (loop=0x5555557fa2b0, mode=mode@entry=UV_RUN_DEFAULT) at ../src/unix/core.c:275
#18 0x000055555555fc75 in EventBase_beginLoop (eventBase=0x5555557fa268) at util/events/libuv/EventBase.c:83
#19 0x00005555555b1fcc in Core_main (argc=<optimized out>, argv=<optimized out>) at admin/angel/Core.c:379
#20 0x0000555555558f06 in main (argc=4, argv=0x7fffffffe548) at client/cjdroute2.c:536

(gdb) 
# git log | head -n 1

commit 116fa2aff419950403eba3530c4e2d2e63db8819
# git pull

remote: Counting objects: 9, done.
remote: Total 9 (delta 7), reused 7 (delta 7), pack-reused 2
Unpacking objects: 100% (9/9), done.
From https://github.com/cjdelisle/cjdns
   359c72f..113d160  crashey    -> origin/crashey
Already up-to-date.

**Comment by ansuz** [comment]
duplicate of number #110
