### ISSUE TITLE
contrib/docker/run: builder err 

### ISSUE THREAD

**Issue by wfleurant** [hyperboria/cjdns#143]
i think this was fixed in cjdelisle/cjdns:crashey

```
Linking C executable contrib/c/publictoip6.c
Linking C executable contrib/c/privatetopublic.c
Building C object net/UpperDistributor.c complete
Building C object net/SwitchPinger.c complete
Building C object net/ControlHandler.c complete
Building C object util/Security_admin.c complete
Building C object net/SessionManager_admin.c complete
Building C object util/events/libuv/FileNo_admin.c complete
Building C object net/EventEmitter.c complete
Building C object util/log/IndirectLog.c complete
Building C object util/platform/netdev/NetDev.c complete
Building C object util/Security.c complete
Building C object net/SwitchPinger_admin.c complete
Building C object memory/Allocator_admin.c complete
Building C object interface/FramingIface.c complete
Building C object util/events/libuv/FileNo.c complete
Total build time: 7262ms.
/src/node_build/builder.js:485
            if (err) { throw err; }
                             ^
Error: gcc -c -x cpp-output -o build_linux/tunnel_RouteGen_admin_c.o -std=c99 -Wall -Wextra -Werror -Wno-pointer-sign -pedantic -D linux=1 -D CJD_PACKAGE_VERSION="cjdns-0.3-3823-g7f5caec-dirty" -Wno-unused-parameter -D Log_DEBUG -g -D NumberCompress_TYPE=v3x5x8 -D Identity_CHECK=1 -D Allocator_USE_CANARIES=1 -D PARANOIA=1 -DHAS_ETH_INTERFACE=1 -fPIE -fno-stack-protector -fstack-protector-all -Wstack-protector -O3 build_linux/tunnel_RouteGen_admin_c.o.i

tunnel/RouteGen_admin.c: In function 'commit':
tunnel/RouteGen_admin.c:181:11: error: variable 'error' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
     char* error = "none";
           ^
cc1: all warnings being treated as errors

    at error (/src/node_build/builder.js:53:15)
    at /src/node_build/builder.js:122:22
    at /src/node_build/builder.js:92:13
    at ChildProcess.<anonymous> (/src/tools/lib/Semaphore.js:7:30)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1016:16)
    at Socket.<anonymous> (child_process.js:1184:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:484:11)

```

**Comment by ghost** [comment]
Yeah I fixed this one in crashey :) -- might even be in master already? Anyhow, someone needs to have a look at whether the automatic hub.docker.com builds work.

**Comment by wfleurant** [comment]
Will do
