### ISSUE TITLE
ipv6_route.h is missing

### ISSUE THREAD

**Issue by skadesh** [hyperboria/cjdns#145]
I am following the instructions at the android repository and am unable to build cjdns with android_do, it gives this error:

```
Error: gcc -c -x cpp-output -o build_linux/memory_Allocator_c.o -std=c99 -Wall -Wextra -Werror -Wno-pointer-sign -pedantic -D linux=1 -D CJD_PACKAGE_VERSION="unknown" -Wno-unused-parameter -D Log_DEBUG -g -D NumberCompress_TYPE=v3x5x8 -D Identity_CHECK=1 -D Allocator_USE_CANARIES=1 -D PARANOIA=1 -DHAS_ETH_INTERFACE=1 -fPIE -Dandroid=1 -fno-stack-protector -fstack-protector-all -Wstack-protector -O3 build_linux/memory_Allocator_c.o.i

memory/Allocator.c: In function 'Allocator_new':
memory/Allocator.c:790:51: error: integer constant is too large for its type [-Werror]
             .canary = (unsigned long) Constant_rand64(),
                                                   ^
memory/Allocator.c:791:55: error: integer constant is too large for its type [-Werror]
             .nextCanary = (unsigned long) Constant_rand64(),
                                                       ^
cc1: all warnings being treated as errors

    at error (/Users/simonk/.Trash/cjdns-master/node_build/builder.js:53:15)
    at /Users/simonk/.Trash/cjdns-master/node_build/builder.js:122:22
    at /Users/simonk/.Trash/cjdns-master/node_build/builder.js:92:13
    at ChildProcess.<anonymous> (/Users/simonk/.Trash/cjdns-master/tools/lib/Semaphore.js:7:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

```

**Comment by skadesh** [comment]
It also says 

```
Failed to get SECCOMP, compile failure: [/tmp/jsmake-c1078031dfb331bc6092:4:27: fatal error: linux/seccomp.h: No such file or directory
 #include <linux/seccomp.h>
                           ^
compilation terminated.
]
```

**Comment by wfleurant** [comment]
the memory/\* issue is the real one. try cjdlisle/cjdns:crashey

**Comment by skadesh** [comment]
arm-linux-androideabi-gcc: error: build_linux/dependencies/libuv/out/Release/libuv.a: No such file or directory

```
at error (/Users/simonk/Downloads/cjdns-crashey-2/node_build/builder.js:53:15)
at /Users/simonk/Downloads/cjdns-crashey-2/node_build/builder.js:122:22
at /Users/simonk/Downloads/cjdns-crashey-2/node_build/builder.js:92:13
at ChildProcess.<anonymous> (/Users/simonk/Downloads/cjdns-crashey-2/tools/lib/Semaphore.js:7:30)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:852:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
```

real    0m19.307s
user    0m51.046s
sys 0m9.403s
cp: cjdroute: No such file or directory

When I build the crashy branch of the other repository

**Comment by xelad1** [comment]
@Such1337Hax0r Did you ever find a fix for that last error? I'm getting something similar:

```
arm-linux-androideabi-gcc: error: build_linux/dependencies/libuv/out/Release/libuv.a: No such file or directory

    at error (/Users/alexanderdajani/Documents/GitRepos/android/cjdns-src/node_build/builder.js:53:15)
    at /Users/alexanderdajani/Documents/GitRepos/android/cjdns-src/node_build/builder.js:122:22
    at /Users/alexanderdajani/Documents/GitRepos/android/cjdns-src/node_build/builder.js:92:13
    at ChildProcess.<anonymous> (/Users/alexanderdajani/Documents/GitRepos/android/cjdns-src/tools/lib/Semaphore.js:7:30)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
