### ISSUE TITLE
Build failure on ARMv7 with gcc 6.2.0

### ISSUE THREAD

**Issue by clehner** [hyperboria/cjdns#147]
```
...
Building C object crypto/random/test/DeterminentRandomSeed.c complete
Building C object dht/dhtcore/RumorMill.c complete
Building C object util/Order.c complete
Building C object dht/DHTModuleRegistry.c complete
Total build time: 150361ms.
/home/cel/src/cjdns/node_build/builder.js:485
            if (err) { throw err; }
                       ^

Error: gcc -c -x cpp-output -o build_linux/crypto_Sign_c.o -std=c99 -Wall -Wextra -Werror -Wno-pointer-sign -pedantic -D linux=1 -D CJD_PACKAGE_VERSION="cjdns-v18" -Wno-unused-parameter -D Log_DEBUG -g -D NumberCompress_TYPE=v3x5x8 -D Identity_CHECK=1 -D Allocator_USE_CANARIES=1 -D PARANOIA=1 -DHAS_ETH_INTERFACE=1 -fPIE -fno-stack-protector -fstack-protector-all -Wstack-protector -O3 build_linux/crypto_Sign_c.o.i

In file included from build_linux/dependencies/cnacl/jsbuild/include_internal/crypto_int32.h:1:0,
                 from ./node_build/dependencies/cnacl/crypto_sign/ed25519/ref10/fe.h:4,
                 from ./node_build/dependencies/cnacl/crypto_sign/ed25519/ref10/ge.h:18,
                 from crypto/Sign.c:18:
build_linux/dependencies/cnacl/jsbuild/include_internal/crypto_types.h:9:26: error: redefinition of typedef ‘crypto_int64’ [-Werror=pedantic]
 typedef signed long long crypto_int64;
                          ^~~~~~~~~~~~
build_linux/dependencies/cnacl/jsbuild/include_internal/crypto_types.h:6:19: note: previous declaration of ‘crypto_int64’ was here
 typedef long long crypto_int64;
                   ^~~~~~~~~~~~
build_linux/dependencies/cnacl/jsbuild/include_internal/crypto_types.h:11:20: error: redefinition of typedef ‘crypto_int32’ [-Werror=pedantic]
 typedef signed int crypto_int32;
                    ^~~~~~~~~~~~
build_linux/dependencies/cnacl/jsbuild/include_internal/crypto_types.h:4:20: note: previous declaration of ‘crypto_int32’ was here
 typedef signed int crypto_int32;
                    ^~~~~~~~~~~~
cc1: all warnings being treated as errors

    at error (/home/cel/src/cjdns/node_build/builder.js:53:15)
    at /home/cel/src/cjdns/node_build/builder.js:122:22
    at /home/cel/src/cjdns/node_build/builder.js:92:13
    at ChildProcess.<anonymous> (/home/cel/src/cjdns/tools/lib/Semaphore.js:7:30)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
```
gcc version 6.2.0 20161010 (Raspbian 6.2.0-6+rpi1)
cjdns@master (6781eddb2b206da6d9e14fa79fab507c9f154acf)

**Comment by kylerschin** [comment]
Works on Pine64. ping of 12ms to h.cjdns.ca.

**Comment by kylerschin** [comment]
@clehner Suggest getting the `node` repo from https://learn.adafruit.com/apt-adafruit-com/overiew

**Comment by kylerchin** [comment]
https://github.com/hyperboria/bugs/issues/6#issuecomment-162244016
