### ISSUE TITLE
Fails to compile: CPU you selected does not support x86-64 instruction set

### ISSUE THREAD

**Issue by Weuxel** [hyperboria/cjdns#15]
Commit: dc7eaf676cb83f13ba3e76a1bd0f2e093e6d6e1b

```
~/cjdns# ./do
Initialize 2ms
Build NaCl
Creating directories
Link time optimization not supported [/tmp/jsmake-2741376c515d81d4763a:1:0: error: CPU you selected does not support x86-64 instruction set
]
randombytes/devurandom.c:1:0: error: CPU you selected does not support x86-64 instruction set

Total build time: 211ms.

/root/cjdns/build_linux/dependencies/cnacl/node_build/RandomBytes.js:13
        if (retCode) { throw new Error('failed to compile'); }
                             ^
Error: failed to compile
    at /root/cjdns/build_linux/dependencies/cnacl/node_build/RandomBytes.js:13:30
    at /root/cjdns/node_build/builder.js:85:13
    at ChildProcess.<anonymous> (/root/cjdns/node_build/Semaphore.js:7:30)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)
```

Cjdns does not compile on VPS with CPU model_name model name QEMU Virtual CPU version 1.0.
Older versions compiled fine.

**Comment by lgierth** [comment]
Could I get that VPS' /proc/cpuinfo?

**Comment by lgierth** [comment]
The issue is probably either that the NaCl build doesn't support this QEMU CPU (i.e. correctly identifies it as an x86_64 CPU), or that this CPU simply isn't x86_64.

Have a look, maybe you can figure it out.

**Comment by Weuxel** [comment]
Here you go:

    cat /proc/cpuinfo 
    processor	: 0
    vendor_id	: GenuineIntel
    cpu family	: 6
    model		: 2
    model name	: QEMU Virtual CPU version 1.0
    stepping	: 3
    microcode	: 0x1
    cpu MHz		: 2299.998
    cache size	: 4096 KB
    fpu		: yes
    fpu_exception	: yes
    cpuid level	: 4
    wp		: yes
    flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm up rep_good nopl pni vmx cx16 popcnt hypervisor lahf_lm
    bogomips	: 4599.99
    clflush size	: 64
    cache_alignment	: 64
    address sizes	: 40 bits physical, 48 bits virtual
    power management:
    
CPU is x86_64:

    uname -m
    x86_64

The problem does not occur with this command:

     CROSS=y ./do
