### ISSUE TITLE
crashey: interface/UDPInterface.c:223:45: error: missing ...

### ISSUE THREAD

**Issue by wfleurant** [hyperboria/cjdns#180]
machine  
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

```

gcc

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 

```

error

```
Total build time: 26216ms.
/home/builder/cjdns/node_build/builder.js:486
            if (err) { throw err; }
                       ^

Error: gcc -c -x cpp-output -o build_linux/interface_UDPInterface_c.o -std=c99 -Wall -Wextra -Werror -Wno-pointer-sign -Wmissing-prototypes -pedantic -D linux=1 -D CJD_PACKAGE_VERSION="cjdns-v20.2-27-g3da23d5" -Wno-unused-parameter -D Log_DEBUG -g -D NumberCompress_TYPE=v3x5x8 -D Identity_CHECK=1 -D Allocator_USE_CANARIES=1 -D PARANOIA=1 -march=native -DHAS_ETH_INTERFACE=1 -fPIE -D_FORTIFY_SOURCE=2 -fno-stack-protector -fstack-protector-all -Wstack-protector -O3 build_linux/interface_UDPInterface_c.o.i

interface/UDPInterface.c: In function ‘UDPInterface_new’:
interface/UDPInterface.c:223:45: error: missing initializer for field ‘Identity_verifier’ of ‘struct UDPInterface_pvt’ [-Werror=missing-field-initializers]
         Allocator_clone(alloc, (&(struct UDPInterface_pvt) {
                                             ^
interface/UDPInterface.c:48:19: note: ‘Identity_verifier’ declared here
interface/UDPInterface.c:223:344: error: missing initializer for field ‘Identity_verifier’ of ‘struct UDPInterface_pvt’ [-Werror=missing-field-initializers]
interface/UDPInterface.c:48:19: note: ‘Identity_verifier’ declared here
cc1: all warnings being treated as errors

    at error (/home/builder/cjdns/node_build/builder.js:53:15)
    at /home/builder/cjdns/node_build/builder.js:122:22
    at /home/builder/cjdns/node_build/builder.js:92:13
    at ChildProcess.<anonymous> (/home/builder/cjdns/tools/lib/Semaphore.js:7:30)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)


```

**Comment by wfleurant** [comment]
i could have at least provided the revision... do'h (fix went in a day or so later)
