### ISSUE TITLE
authorizedPasswords users

### ISSUE THREAD

**Issue by cwchristerw** [hyperboria/cjdns#184]
{
      "user": "cwinfo",
      "password": "Password1"
    },
    {
      "user": "cwchristerw",
      "password": "Password2"
    },
    {
      "user": "7368f0bc33d2b2dd40078097f801fbd6", 
      "password": "Password3"
    }

INFO Configurator.c:135 Checking authorized password 0.
INFO Configurator.c:135 Checking authorized password 1.
INFO Configurator.c:135 Checking authorized password 2.
INFO Configurator.c:159 Adding authorized password #[0] for user [cwinfo].
INFO Configurator.c:159 Adding authorized password #[1] for user [cwchristerw].

Not working properly don't detect users after cwchristerw

    {
      "user": "cwinfo",
      "password": "Password1"
    },
    {
      "user": "cwchriste",
      "password": "Password2"
    },
    {
      "user": "7368f0bc33d2b2dd40078097f801fbd6", 
      "password": "Password3"
    }

INFO Configurator.c:135 Checking authorized password 0.
INFO Configurator.c:135 Checking authorized password 1.
INFO Configurator.c:135 Checking authorized password 2.
INFO Configurator.c:159 Adding authorized password #[0] for user [cwinfo].
INFO Configurator.c:159 Adding authorized password #[1] for user [cwchriste].
INFO Configurator.c:159 Adding authorized password #[2] for user [7368f0bc33d2b2dd40078097f801fbd6].

Detects properly all users

**Comment by progval** [comment]
Hi!

Could you check some variations, to see what is triggering the bug? My config has usernames longer "cwchristerw" so the length alone probably isn't.

**Comment by progval** [comment]
Also, how did you check users are not detected? With `./tools/cexec 'AuthorizedPasswords_list()'`?

**Comment by cwchristerw** [comment]
I'm using docker so it's not possible to do that kind of command

**Comment by kpcyrd** [comment]
you could run the cjdns container with `--net=host`, this would bind the admin port to your machines localhost (assuming you're on linux).

**Comment by cwchristerw** [comment]
> Hi!
> 
> Could you check some variations, to see what is triggering the bug? My config has usernames longer "cwchristerw" so the length alone probably isn't.

When changing cwchristerw -> cwchriste, it works

**Comment by cwchristerw** [comment]
> you could run the cjdns container with `--net=host`, this would bind the admin port to your machines localhost (assuming you're on linux).

Already using but dont know, how to use this command.

**Comment by progval** [comment]
> I'm using docker so it's not possible to do that kind of command

Wouldn't this work? https://docs.docker.com/engine/reference/commandline/exec/

**Comment by cwchristerw** [comment]
It works, but when Dockerfile removes src after building so there is no ./tools/ left after build. Downloading it seperately gives error ...

ON HOST
`docker exec -it cjdns bash`

IN CONTAINER
`cd /src/`
`git clone https://github.com/cjdelisle/cjdns.git`
`cd cjdns`
`./tools/cexec 'AuthorizedPasswords_list()'`

```
bash-4.3# ./tools/cexec 'AuthorizedPasswords_list()'
/src/cjdns/tools/lib/cjdnsadmin/cjdnsadmin.js:149
                    Object.keys(ret.availableFunctions).forEach(function (funcName) {
                           ^

TypeError: Cannot convert undefined or null to object
    at /src/cjdns/tools/lib/cjdnsadmin/cjdnsadmin.js:149:28
    at Object.callback (/src/cjdns/node_modules/nthen/index.js:21:22)
    at Socket.<anonymous> (/src/cjdns/tools/lib/cjdnsadmin/cjdnsadmin.js:191:17)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:549:8)
```

**Comment by progval** [comment]
Can you update the dockerfile to not delete the src?
