### ISSUE TITLE
Traceroute triggers assertion failure [NodeStore.c:616] [(bp && bp != store->selfLink)]

### ISSUE THREAD

**Issue by gloe-ih** [hyperboria/cjdns#2]
Running on 738df10ab5ed263bfc612c1c0dcb168c363ecfe3 and doing a traceroute of any IPv6 address using the admin API errors with a timeout and then cjdroute aborts failing the assertion `[NodeStore.c:616] [(bp && bp != store->selfLink)]`.

A stack trace follows.

```
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cjdroute...done.
Starting program: /usr/bin/cjdroute < cjdroute.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New process 28738]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
process 28738 is executing new program: /usr/bin/cjdroute
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New process 28744]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
process 28744 is executing new program: /usr/bin/cjdroute
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
1425685275 INFO RandomSeed.c:42 Attempting to seed random number generator
1425685275 INFO RandomSeed.c:50 Trying random seed [/dev/urandom] Success
1425685275 INFO RandomSeed.c:56 Trying random seed [sysctl(RANDOM_UUID) (Linux)] Failed
1425685275 INFO RandomSeed.c:50 Trying random seed [/proc/sys/kernel/random/uuid (Linux)] Success
1425685275 INFO RandomSeed.c:64 Seeding random number generator succeeded with [2] sources
1425685275 INFO LibuvEntropyProvider.c:59 Taking clock samples every [1000]ms for random generator
1425685275 DEBUG Pipe.c:231 Pipe [/tmp/cjdns_pipe_furrxbsplh0gwk58xj7yubz9u79ruv] established connection
1425685275 DEBUG UDPAddrIface.c:255 Binding to address [127.0.0.1:11234]
1425685275 DEBUG UDPAddrIface.c:294 Bound to address [127.0.0.1:11234]
1425685275 DEBUG Hermes.c:151 Sending [64] bytes to angel


Assertion failure [NodeStore.c:616] [(bp && bp != store->selfLink)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff7fad700 (LWP 28744)]
0x00007ffff76464b7 in raise () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7ffff7fad700 (LWP 28744)):
#0  0x00007ffff76464b7 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff764788a in abort () from /usr/lib/libc.so.6
#2  0x000055555555986b in Assert_failure (format=format@entry=0x5555555dbb60 "Assertion failure [%s:%d] [%s]\n") at util/Assert.c:32
#3  0x000055555558c07e in handleBadNews (store=0x55555580d358, newReach=3758096383, node=0x55555580d418) at dht/dhtcore/NodeStore.c:616
#4  handleNews (node=node@entry=0x55555580d418, newReach=newReach@entry=3758096383, store=store@entry=0x55555580d358) at dht/dhtcore/NodeStore.c:635
#5  0x0000555555592897 in NodeStore_pathTimeout (nodeStore=0x55555580d358, path=<optimized out>) at dht/dhtcore/NodeStore.c:2254
#6  0x0000555555594251 in onTimeout (pctx=0x5555558b42b8, milliseconds=24800) at dht/dhtcore/RouterModule.c:429
#7  onResponseOrTimeout (data=<optimized out>, milliseconds=24800, vping=0x5555558b42b8) at dht/dhtcore/RouterModule.c:472
#8  0x000055555557330c in callback (ping=0x555555895a38, data=0x0) at util/Pinger.c:55
#9  timeoutCallback (vping=0x555555895a38) at util/Pinger.c:74
#10 0x00005555555d8231 in uv__run_timers (loop=loop@entry=0x5555557fb2b0) at ../src/unix/timer.c:146
#11 0x00005555555ce9a2 in uv_run (loop=0x5555557fb2b0, mode=mode@entry=UV_RUN_DEFAULT) at ../src/unix/core.c:275
#12 0x000055555555dec5 in EventBase_beginLoop (eventBase=eventBase@entry=0x5555557fb268) at util/events/libuv/EventBase.c:83
#13 0x00005555555b1776 in Core_main (argc=<optimized out>, argv=0x7fffffffebb8) at admin/angel/Core.c:373
#14 0x00005555555b6baa in main (argc=3, argv=0x7fffffffebb8) at admin/angel/cjdroute2.c:408
1425685275 INFO RandomSeed.c:42 Attempting to seed random number generator
1425685275 INFO RandomSeed.c:50 Trying random seed [/dev/urandom] Success
1425685275 INFO RandomSeed.c:56 Trying random seed [sysctl(RANDOM_UUID) (Linux)] Failed
1425685275 INFO RandomSeed.c:50 Trying random seed [/proc/sys/kernel/random/uuid (Linux)] Success
1425685275 INFO RandomSeed.c:64 Seeding random number generator succeeded with [2] sources
1425685275 DEBUG AngelInit.c:152 Getting pre-configuration from client
1425685275 DEBUG Pipe.c:231 Pipe [/tmp/cjdns_pipe_client-angel-9ffsqb1h0t6p0h8mklxc2nck91pgfn] established connection
1425685275 DEBUG AngelInit.c:156 Finished getting pre-configuration from client
1425685275 INFO AngelInit.c:183 Initializing core [/usr/bin/cjdroute]
1425685275 DEBUG AngelInit.c:187 Sending pre-configuration to core.
1425685275 DEBUG Pipe.c:134 Buffering a message
1425685275 DEBUG Pipe.c:231 Pipe [/tmp/cjdns_pipe_furrxbsplh0gwk58xj7yubz9u79ruv] established connection
1425685275 DEBUG Pipe.c:253 Sending buffered message
1425685275 DEBUG AngelInit.c:210 Angel_start()
1425685274 INFO cjdroute2.c:513 Cjdns AMD64 64-bit LittleEndian linux +seccomp
1425685274 INFO cjdroute2.c:517 Checking for running instance...
1425685274 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]
1425685274 DEBUG UDPAddrIface.c:294 Bound to address [0.0.0.0:34613]
1425685274 INFO cjdroute2.c:543 Forking angel to background.
1425685274 DEBUG Pipe.c:134 Buffering a message
1425685274 DEBUG cjdroute2.c:580 Sent [192] bytes to angel process
1425685275 DEBUG Pipe.c:231 Pipe [/tmp/cjdns_pipe_client-angel-9ffsqb1h0t6p0h8mklxc2nck91pgfn] established connection
1425685275 DEBUG Pipe.c:253 Sending buffered message
1425685275 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]
1425685275 DEBUG UDPAddrIface.c:294 Bound to address [0.0.0.0:45882]
1425685275 INFO Configurator.c:438 Setting up ETHInterface [0].
1425685275 INFO Configurator.c:441 Binding to device [adhoc0].
1425685275 INFO Configurator.c:383 Setting beacon mode on ETHInterface to [2].
1425685275 INFO Configurator.c:455 ETHInterface should connect to a specific node.
```

**Comment by lgierth** [comment]
Still reproducible

**Comment by lgierth** [comment]
Closing in favor of #53
