### ISSUE TITLE
cnacl fails to compile due to a missing x86_AVX node build plan

### ISSUE THREAD

**Issue by yuvallanger** [hyperboria/cjdns#21]
When I run `./do`, I get this output:

```
### Installing node.js (you can bypass this step by manually installing node.js v0.8.15 or newer)


==> Downloading http://nodejs.org/dist/v0.10.24/node-v0.10.24-linux-x86.tar.gz with wget... DONE!
==> Verifying the checksum of the downloaded archive... DONE!
==> Extracting the downloaded archive... DONE!

Initialize 7ms
Copy dependencies
Compiler supports link time optimization
Build NaCl
Creating directories
Getting system type
System is [x86_AVX]
Total build time: 2748ms.

/home/cjdns/cjdns/build_linux/dependencies/cnacl/node_build/make.js:72
    throw new Error("build with no premade plan, TODO: generate one");
          ^
Error: build with no premade plan, TODO: generate one
    at getPlan (/home/cjdns/cjdns/build_linux/dependencies/cnacl/node_build/make.js:72:11)
    at /home/cjdns/cjdns/build_linux/dependencies/cnacl/node_build/make.js:134:18
    at /home/cjdns/cjdns/build_linux/dependencies/cnacl/node_build/AbiName.js:11:5
    at /home/cjdns/cjdns/node_build/builder.js:85:13
    at ChildProcess.<anonymous> (/home/cjdns/cjdns/node_build/Semaphore.js:7:30)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)
```

**Comment by yuvallanger** [comment]
I've used the `master` branch, not the `crashey` branch, which doesn't have this problem.

Sorry for the false post.
