### ISSUE TITLE
Fails to compile on Mac OS X

### ISSUE THREAD

**Issue by Fil** [hyperboria/cjdns#25]
```
Building C object io/ArrayReader.c complete
Building C object util/platform/Sockaddr.c complete
Linking C executable contrib/c/publictoip6.c
Linking C executable contrib/c/privatetopublic.c
Building C object crypto/random/libuv/LibuvEntropyProvider.c complete
Building C object util/events/libuv/Timeout.c complete
Building C object crypto/CryptoAuth.c complete
Building C object tunnel/IpTunnel.c complete
Total build time: 7994ms.
/Users/fil/Source/cjdns/node_build/builder.js:713
            if (err) { throw err; }
                             ^
Error: gcc -Wl,-pie,-flto,-O3 -o build_darwin/contrib_c_publictoip6_c build_darwin/util_Assert_c.o,build_darwin/util_Bits_c.o,build_darwin/memory_Allocator_c.o,build_darwin/util_CString_c.o,build_darwin/benc_String_c.o,build_darwin/crypto_AddressCalc_c.o,build_darwin/crypto_Key_c.o,build_darwin/util_Hex_c.o,build_darwin/util_platform_Sockaddr_c.o,build_darwin/util_AddrTools_c.o,build_darwin/contrib_c_publictoip6_c.o build_darwin/dependencies/cnacl/jsbuild/libnacl.a,build_darwin/dependencies/libuv/out/Release/libuv.a,-lpthread,-framework,CoreServices

clang: error: no such file or directory: 'build_darwin/dependencies/libuv/out/Release/libuv.a'

...
```

**Comment by lgierth** [comment]
Could you paste the complete output of `./do`?

**Comment by Fil** [comment]
```
$ git show
commit dc7eaf676cb83f13ba3e76a1bd0f2e093e6d6e1b

$ ./do
Initialize 2ms
testing python python
Build Libuv
Compiler supports link time optimization
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
['/Users/fil/Source/cjdns/build_darwin/dependencies/libuv/uv.gyp', '-I', '/Users/fil/Source/cjdns/build_darwin/dependencies/libuv/common.gypi', '--depth=.', '-f', 'make', '-Goutput_dir=/Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out', '--generator-output', '/Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out', '-Dgcc_version=42', '-Dclang=1', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dlibrary=static_library', '-Dcomponent=static_library']
  rm -f /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/libuv.a && ./gyp-mac-tool filter-libtool libtool  -static -o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/libuv.a /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/fs-poll.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/inet.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/uv-common.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/version.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/async.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/core.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/dl.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/fs.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/getaddrinfo.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/loop.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/loop-watcher.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/pipe.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/poll.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/process.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/signal.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/stream.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/tcp.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/thread.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/threadpool.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/timer.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/tty.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/udp.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/proctitle.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/darwin.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/fsevents.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/darwin-proctitle.o /Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/obj.target/libuv/src/unix/kqueue.o
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [/Users/fil/Source/cjdns/build_darwin/dependencies/libuv/out/Release/libuv.a] Error 1
Configure 1020ms
Scan for out of date files 3ms
Building C object contrib/c/publictoip6.c complete
Building C object contrib/c/privatetopublic.c complete
Building C object crypto/random/randombytes.c complete
Building C object admin/angel/cjdroute2.c complete
Building C object contrib/c/makekeys.c complete
Building C object util/AddrTools.c complete
Building C object crypto/Key.c complete
Building C object test/testcjdroute.c complete
Building C object benc/String.c complete
Building C object util/CString.c complete
Searching for SECCOMP
SECCOMP is only available on linux
Building C object contrib/c/sybilsim.c complete
Building C object util/Assert.c complete
Building C object util/Hex.c complete
Building C object crypto/AddressCalc.c complete
Building C object memory/MallocAllocator.c complete
Building C object dht/Address.c complete
Building C object crypto/random/seed/RandomSeed.c complete
Building C object crypto/random/Random.c complete
Building C object util/log/Log.c complete
Building C object memory/Allocator.c complete
Building C object exception/Except.c complete
Building C object util/SysInfo.c complete
Building C object util/log/FileWriterLog.c complete
Building C object util/ArchInfo.c complete
Building C object util/events/libuv/Process.c complete
Building C object io/FileWriter.c complete
Building C object io/FileReader.c complete
Building C object util/events/libuv/Time.c complete
Building C object benc/serialization/standard/BencMessageWriter.c complete
Building C object benc/serialization/standard/BencMessageReader.c complete
Building C object benc/List.c complete
Building C object net/Benchmark.c complete
Building C object admin/angel/InterfaceWaiter.c complete
Building C object util/events/libuv/Pipe.c complete
Building C object util/version/Version.c complete
Building C object admin/angel/Hermes.c complete
Building C object benc/serialization/json/JsonBencSerializer.c complete
Building C object util/Bits.c complete
Building C object admin/angel/AngelInit.c complete
Building C object admin/angel/Core.c complete
Building C object admin/Configurator.c complete
Building C object benc/Dict.c complete
Building C object admin/AdminClient.c complete
Building C object util/events/libuv/EventBase.c complete
Building C object ./interface/tuntap/windows/test/TAPInterface_root_test.c complete
Building C object util/platform/Sockaddr.c complete
Linking C executable contrib/c/publictoip6.c
Linking C executable contrib/c/privatetopublic.c
Building C object ./interface/tuntap/windows/test/TAPDevice_root_test.c complete
Building C object ./util/platform/test/Sockaddr_test.c complete
Building C object ./interface/tuntap/test/TUNInterface_ipv6_root_test.c complete
Building C object ./interface/tuntap/test/TUNInterface_ipv4_root_test.c complete
Building C object ./interface/tuntap/test/TAPWrapper_root_test.c complete
Building C object ./util/test/UniqueName_test.c complete
Building C object ./dht/dhtcore/test/VersionList_test.c complete
Building C object ./interface/tuntap/test/BSDMessageTypeWrapper_test.c complete
Building C object ./dht/dhtcore/test/NodeStore_test.c complete
Building C object ./util/test/Seccomp_test.c complete
Building C object ./crypto/random/test/Random_test.c complete
Building C object ./util/test/Identity_test.c complete
Building C object ./util/test/Hex_test.c complete
Building C object ./util/test/Map_test.c complete
Building C object ./util/test/Endian_test.c complete
Building C object ./util/test/Process_test.c complete
Building C object ./util/test/Bits_test.c complete
Building C object ./util/test/Base32_test.c complete
Building C object ./util/test/Checksum_test.c complete
Building C object ./util/test/ArchInfo_test.c complete
Building C object ./util/test/AverageRoller_test.c complete
Building C object ./util/test/Base10_test.c complete
Building C object ./util/test/AddrTools_test.c complete
Building C object ./switch/test/PenaltyFloat_test.c complete
Building C object tunnel/IpTunnel.c complete
Building C object ./switch/test/LabelSplicer_test.c complete
Building C object ./memory/test/Allocator_test.c complete
Building C object crypto/CryptoAuth.c complete
Building C object ./io/test/FileReader_test.c complete
Building C object ./interface/test/FramingIface_test.c complete
Building C object ./switch/test/NumberCompress_test.c complete
Building C object ./interface/test/FramingIface_fuzz_test.c complete
Building C object ./dht/test/DHTModules_handleOutgoing_test.c complete
Building C object ./dht/test/DHTModules_handleIncoming_test.c complete
Building C object ./tunnel/test/IpTunnel_test.c complete
Building C object ./test/printIp_test.c complete
Building C object ./crypto/test/ReplayProtector_test.c complete
Building C object ./switch/test/EncodingScheme_test.c complete
Building C object io/ArrayWriter.c complete
Building C object ./test/CryptoAddress_test.c complete
Building C object ./crypto/test/CryptoAuth_unit_test.c complete
Building C object io/ArrayReader.c complete
Building C object crypto/random/libuv/LibuvEntropyProvider.c complete
Building C object util/events/libuv/Timeout.c complete
Building C object ./test/Beacon_test.c complete
Building C object ./crypto/test/CryptoAuth_test.c complete
Building C object crypto/random/seed/SystemRandomSeed.c complete
Total build time: 7120ms.
/Users/fil/Source/cjdns/node_build/builder.js:713
            if (err) { throw err; }
                             ^
Error: gcc -Wl,-pie,-flto,-O3 -o build_darwin/contrib_c_publictoip6_c build_darwin/util_Assert_c.o,build_darwin/util_Bits_c.o,build_darwin/memory_Allocator_c.o,build_darwin/util_CString_c.o,build_darwin/benc_String_c.o,build_darwin/crypto_AddressCalc_c.o,build_darwin/crypto_Key_c.o,build_darwin/util_Hex_c.o,build_darwin/util_platform_Sockaddr_c.o,build_darwin/util_AddrTools_c.o,build_darwin/contrib_c_publictoip6_c.o build_darwin/dependencies/cnacl/jsbuild/libnacl.a,build_darwin/dependencies/libuv/out/Release/libuv.a,-lpthread,-framework,CoreServices

clang: error: no such file or directory: 'build_darwin/dependencies/libuv/out/Release/libuv.a'

    at error (/Users/fil/Source/cjdns/node_build/builder.js:52:15)
    at /Users/fil/Source/cjdns/node_build/builder.js:115:22
    at /Users/fil/Source/cjdns/node_build/builder.js:85:13
    at ChildProcess.<anonymous> (/Users/fil/Source/cjdns/node_build/Semaphore.js:7:30)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

(PS: going offline now)

**Comment by lgierth** [comment]
I don't have an OS X machine handy, but I know it can generally be tricky to get a development environment working on OS X.

This actual error is this: `libtool: unrecognized option `-static'`

Try fixing your libtool installation, e.g. like this: https://github.com/apiaryio/snowcrash/issues/93#issuecomment-39346375

**Comment by Fil** [comment]
Thank you, it worked!
