### ISSUE TITLE
Segfault after a few minutes

### ISSUE THREAD

**Issue by viric** [hyperboria/cjdns#28]
This is x86_64-linux, without any tun device. Running 78e13484b6.

Happens after less than 10 minutes of running, usually.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f026815c159 in Iface_next ()
(gdb) bt
#0  0x00007f026815c159 in Iface_next ()
#1  0x00007f026815c9cb in sendToTunIf ()
#2  0x00007f026815cd38 in incomingFromUpperDistributorIf ()
#3  0x00007f026815b703 in Iface_send ()
#4  0x00007f026815b852 in Iface_next ()
#5  0x00007f026815bc0d in incomingFromSessionManagerIf ()
#6  0x00007f026815a331 in Iface_send ()
#7  0x00007f026815a480 in Iface_next ()
#8  0x00007f026815b043 in incomingFromSessionManagerIf ()
#9  0x00007f02681547a8 in Iface_send ()
#10 0x00007f02681548f7 in Iface_next ()
#11 0x00007f026815656c in incomingFromSwitchIf ()
#12 0x00007f0268159a09 in Iface_send ()
#13 0x00007f0268159b58 in Iface_next ()
#14 0x00007f0268159e41 in incomingFromSwitchIf ()
#15 0x00007f026813fdd4 in Iface_send ()
#16 0x00007f026813ff23 in Iface_next ()
#17 0x00007f026814111f in receiveMessage ()
#18 0x00007f0268144242 in Iface_send ()
#19 0x00007f0268144391 in Iface_next ()
#20 0x00007f0268145e74 in receivedPostCryptoAuth ()
#21 0x00007f0268147026 in handleIncomingFromWire ()
#22 0x00007f026813c51e in Iface_send ()
#23 0x00007f026813cd80 in incoming ()
#24 0x00007f02681aaa07 in uv__udp_recvmsg () at ../src/unix/udp.c:219
#25 0x00007f02681aa7f8 in uv__udp_io () at ../src/unix/udp.c:157
#26 0x00007f02681abcc7 in uv__io_poll () at ../src/unix/linux-core.c:271
#27 0x00007f026819b6d0 in uv_run () at ../src/unix/core.c:284
#28 0x00007f0268104608 in EventBase_beginLoop ()
#29 0x00007f026815ed34 in Core_main ()
#30 0x00007f0268166df3 in main ()
```

Sorry for the lack of some src line numbers/files. I don't know the reason.

**Comment by viric** [comment]
It seems fixed.

**Comment by lgierth** [comment]
Coolio!
