### ISSUE TITLE
Assertion failure in NodeStore after 2 days

### ISSUE THREAD

**Issue by viric** [hyperboria/cjdns#30]
Running crashey 80cb9c090bbd4fee74c12460cfb11f973ff8cda6 in x86_64-linux, without tun device, after two days I got:

Assertion failure [NodeStore.c:419] [(r < Node_getReach(link->parent) && r != 0)]

**Comment by viric** [comment]
Here is the backtrace:
```
(gdb) bt
#0  0x00007f62c0ab6a5e in raise ()
   from /nix/store/cj7a81wsm1ijwwpkks3725661h3263p5-glibc-2.13/lib/libc.so.6
#1  0x00007f62c0ab7f16 in abort ()
   from /nix/store/cj7a81wsm1ijwwpkks3725661h3263p5-glibc-2.13/lib/libc.so.6
#2  0x00007f62c146fffb in Assert_failure (
    format=0x7f62c14e9000 "Assertion failure [%s:%d] [%s]\n") at util/Assert.c:32
#3  0x00007f62c148ce25 in guessReachOfChild (link=0x7f62c263e778)
    at dht/dhtcore/NodeStore.c:419
#4  0x00007f62c14901f7 in linkNodes (parent=0x7f62c248d048, child=0x7f62c23989c8, 
    cannonicalLabel=14293580792343822336, linkStateDiff=0, 
    inverseLinkEncodingFormNumber=0, discoveredPath=3202145680103, store=0x7f62c22cd588)
    at dht/dhtcore/NodeStore.c:816
#5  0x00007f62c1490576 in discoverLinkC (store=0x7f62c22cd588, closestKnown=Unhandled dwarf expression opcode 0xf3
)
    at dht/dhtcore/NodeStore.c:1059
#6  0x00007f62c1492b7f in discoverLink (nodeStore=0x7f62c22cd588, addr=0x7fff231c85e0, 
    scheme=Unhandled dwarf expression opcode 0xf3
) at dht/dhtcore/NodeStore.c:1192
#7  NodeStore_discoverNode (nodeStore=0x7f62c22cd588, addr=0x7fff231c85e0, scheme=Unhandled dwarf expression opcode 0xf3
)
    at dht/dhtcore/NodeStore.c:1516
#8  0x00007f62c1498bbb in onResponseOrTimeout (data=Unhandled dwarf expression opcode 0xf3
) at dht/dhtcore/RouterModule.c:514
#9  0x00007f62c149898a in callback (data=0x7f62c25289e8, pinger=Unhandled dwarf expression opcode 0xf3
) at util/Pinger.c:55
#10 Pinger_pongReceived (data=0x7f62c25289e8, pinger=Unhandled dwarf expression opcode 0xf3
) at util/Pinger.c:167
#11 0x00007f62c1498e3c in handleIncoming (message=0x7fff231c8430, 
    vcontext=0x7f62c22a66d8) at dht/dhtcore/RouterModule.c:459
#12 0x00007f62c148acca in DHTModuleRegistry_handleIncoming (message=0x7fff231c8430, 
    registry=Unhandled dwarf expression opcode 0xf3
) at dht/DHTModuleRegistry.c:63
#13 0x00007f62c14a1bf4 in incomingMsg (msg=0x7f62c248a658, eventIf=0x7f62c22c3688)
    at dht/Pathfinder.c:385
#14 incomingFromEventIf (msg=0x7f62c248a658, eventIf=0x7f62c22c3688)
    at dht/Pathfinder.c:415
#15 0x00007f62c14b3f64 in Iface_send (vASynchronizer=0x7f62c22c39b8)
    at ./interface/Iface.h:69
#16 timeoutTrigger (vASynchronizer=0x7f62c22c39b8) at interface/ASynchronizer.c:69
#17 0x00007f62c14e5561 in uv__run_timers (loop=0x7f62c22a32b0) at ../src/unix/timer.c:146
#18 0x00007f62c14dbd12 in uv_run (loop=0x7f62c22a32b0, mode=UV_RUN_DEFAULT)
    at ../src/unix/core.c:275
#19 0x00007f62c1475535 in EventBase_beginLoop (eventBase=0x7f62c22a3268)
    at util/events/libuv/EventBase.c:83
#20 0x00007f62c14c15ee in Core_main (argc=Unhandled dwarf expression opcode 0xf3
) at admin/angel/Core.c:326
#21 0x00007f62c146ed68 in main (argc=3, argv=0x7fff231c8f38) at client/cjdroute2.c:462
```

**Comment by viric** [comment]
By now it seems fixed, after 48h running. I'll report if I see this again.
