### ISSUE TITLE
build fails with debugging enabled

### ISSUE THREAD

**Issue by dangowrt** [hyperboria/cjdns#50]
I'm really not so much into this whole JavaScript story, someone please give a hand here:
```
/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_build/builder.js:231
            throw err;
                  ^
ReferenceError: __FILE__ is not defined
Content: [ return '"'+__FILE__.substring(__FILE__.lastIndexOf('/')+1)+'"'; ]
    at Function.eval (eval at <anonymous> (/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_build/builder.js:213:24), <anonymous>:3:13)
    at /usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_build/builder.js:221:22
    at Object.ret.nThen (/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_modules/nthen/lib/nthen.js:32:21)
    at nThen (/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_modules/nthen/lib/nthen.js:63:16)
    at execJs (/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_build/builder.js:209:5)
    at /usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_build/builder.js:269:9
    at Object.ret.nThen (/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_modules/nthen/lib/nthen.js:32:21)
    at nThen (/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_modules/nthen/lib/nthen.js:63:16)
    at preprocessBlock (/usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_build/builder.js:265:5)
    at /usr/src/openwrt/build_dir/target-arm_mpcore_musl-1.1.7_eabi/cjdns-2303ce6585f62f7e8d3cdb1983c0c8e08385ea68/node_build/builder.js:310:13
```

**Comment by lgierth** [comment]
Is this still happening? I've seen similar issue myself, but could never quite pin it down
