### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by IlyaBizyaev** [hyperboria/cjdns#97]
The `./do` command returned ": No such file or directory" error. I used `dos2unix ./*` and ran it again. Here is the output:
```
Initialize 2ms
{"isLLVM":false,"isClang":false,"isGCC":true,"version":"5.2.1"}
Copy dependencies
Compiler supports link time optimization
Build NaCl
Creating directories
Getting system type
System is [amd64]
Using premade plan at [node_build/plans/amd64_plan.json]
Creating system specific integer type headers
beginning build
implementations generated
Compiling jsbuild/objects_internal/crypto_hashblocks_sha512_inplace_blocks.c.o
Compiling jsbuild/objects_internal/crypto_scalarmult_curve25519_donna_c64_base.c.o
Compiling jsbuild/objects_internal/crypto_scalarmult_curve25519_donna_c64_smult.c.o
Compiling jsbuild/objects_internal/crypto_hash_sha512_ref_hash.c.o
In file included from jsbuild/include_internal/crypto_scalarmult_curve25519/crypto_scalarmult.h:4:0,
                 from crypto_scalarmult/curve25519/donna_c64/base.c:1:
jsbuild/include/crypto_scalarmult_curve25519.h:4:54: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before numeric constant
 #define crypto_scalarmult_curve25519_donna_c64_BYTES 32
                                                      ^
jsbuild/include/crypto_scalarmult_curve25519.h:24:2: note: in expansion of macro ‘crypto_scalarmult_curve25519_donna_c64_BYTES’
 #define crypto_scalarmult_curve25519_IMPLEMENTATION "crypto_scalarmult/curve25519/donna_c64"
  ^
crypto_scalarmult/curve25519/donna_c64/base.c:5:28: error: expected identifier or ‘(’ before ‘unsigned’
 int crypto_scalarmult_base(unsigned char *q,const unsigned char *n)
                            ^

Total build time: 823ms.

/home/ilya/cjdns/build_linux/dependencies/cnacl/node_build/PlanRunner.js:184
      if (retCode !== 0) { throw new Error('failed to compile'); }
                                 ^
Error: failed to compile
    at /home/ilya/cjdns/build_linux/dependencies/cnacl/node_build/PlanRunner.js:184:34
    at /home/ilya/cjdns/node_build/builder.js:91:13
    at ChildProcess.<anonymous> (/home/ilya/cjdns/node_build/Semaphore.js:7:30)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```
I've got Ubuntu 15.10.

**Comment by IlyaBizyaev** [comment]
Fixed that by running `find ./ -name '*' | xargs dos2unix`.
